# Generated by Django 4.2.5 on 2023-09-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=36, unique=True)),
                ('color', models.CharField(max_length=128)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
